env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'no-console': 0,
  'no-else-return': off,
  'import/extensions': off,
  'consistent-return': off,
  'no-unused-expressions': off,
  'no-plusplus': off
}